### ISSUE TITLE
2 additional (optional) input variables

### ISSUE THREAD

**Issue by philippe-caltech** [telia-oss/terraform-aws-loadbalancer#11]
### Feature request

> How can we improve the module?

It would be nice to have the ability to specify a non-default "true" value for enable_deletion_protection and enable_cross_zone_load_balancing (https://www.terraform.io/docs/providers/aws/r/lb.html).

**Comment by larstobi** [comment]
Closed by https://github.com/telia-oss/terraform-aws-loadbalancer/pull/14
